sudo: required
services:
- docker
language: java
dist: bionic
jdk:
- openjdk11
cache:
  directories:
  - "$HOME/.m2"
env:
  global:
  - DOCKER_IMAGE=rso26/geolocation:1.0.0-SNAPSHOT-$TRAVIS_JOB_NUMBER
  - secure: SkTgOb+BHH7t3S8Bmkbi9NUm9FZK1UOCwlNwmmgYtcf+7f6or83rBfRjBE+g3/LgQuBD0iJXlR8v2Af4MUUOr1a3ga6yIdUoxMulVdjxgEZodiClbllvdT55eyi6SFQWWfr5zxQNxBNaGoGC5EHzeGT8KvFl6+zLO75waWEV+C3+ZBaxuzq3AxSLlHDQsB6xcUUyqlPhZ5hsYwZNH4KUtdAZKf05BADadLjqs2wq57pV5TW/UBxQUNEtGjEFkets/G/eZrqO3+kiwnoT+IrmYbzFiVhPOKr/gjX9DJWufPHgxLySdVBM9WOu9vS29gCM/6CPpiTGpdq+TX0WYLna6bUa8xEMSbvOIVC6hfWRJRpedm2iftcADuGyY27MVVRgOYCGrQsgG9L+avB+RM3vfXtvJ2dnPfLoeqRosCS17JP0zA0GuLrC2BtZGWiPXzkHx30CAU5zEyuwFwGHb8i9TxDzWCj6x/tuSXNz4tojIWUoysnsJRJUlwq3rViL33KrolvQ3pIo4I6KUFsxgIpHGaMl2qaxLuWu7enlTyvvo1Ep3MtK07DK1+Prj0ViC3pfucHMguUjP0hHW1A99/bQzADjTDZN+ujBPA2UHx/CIMqTvL5niL5BozUYScxTNyy7FBMtX1R5yGGBYUIUZXchN+A8w+Ibv5Wo4DZvxjRrkZo=
  - secure: V3VEX+apJXedq5FqHssFGAp+qwimYzb+NcRPu6f6OkHGRX6eNWE/shftWMYU9NiU+oOOVy3ygk5AVnYuWFJPJ/pbtD6cTc0+PLqucymJapcp4xydHY5GTOLf/k5oKXu43mO1+fE12It1At2FPNatRtzdscpXSEBp5mG4MnQESVTjVxwBrBh6YRR6td9nNjVXESHzyRvJ3H9flnZc1bFaqkdNRAIIYMcKNUDQedIjuEXMDtyIms2bqVAR6BrrjkrVTCAsmTolJCmHe6rESmUyWW681782pEMeXoX1nj+hamFTtVMN4TTawHlVgdlYBQm4BidBsqTochjJIZC9FeMsnrZPuK3axC0T+P8tLknOVKQLI9jBZR8Il/LMmBoNFFdE+iiGLabTc6/Cmj6ffsyIwwU6fTm7w0o+EaELf3Ve6KZ0hVLxwvUwhEW3tzE+QBPTNTB1AW7AsLG8V2atLpmwUANDz3Qn+c6q/Bvox0CE3u+z4l2osIjMMmofb9zNrX6VIVCe6JiZ6+nj4HN+R5tyZqNZhmCk5HPl6SeWY1NAIkeObYSfHMLHTxAcfwzilJVTtTXbYjppHunpqAtoPWcC9iMKjn0yQbEpfRoHlR0QbBzZb7M7z7iFbdtUHPi/5V+/sHiWHVnnQK83tXW0ZUfWdOpjs2Td23lEdT+NvFB8o1M=
script:
- mvn clean package -U
- docker build -t "$DOCKER_IMAGE" .
after_success:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push "$DOCKER_IMAGE"