sudo: required
services:
- docker
language: java
dist: bionic
jdk:
- openjdk11
cache:
  directories:
  - "$HOME/.m2"
env:
  global:
  - DOCKER_IMAGE=rso26/geolocation:1.0.0-SNAPSHOT-$TRAVIS_JOB_NUMBER
  - secure: NgSIJYBti7mErimKdBuvZtAF9SjEa1lpY33d8zV34BYgou3n5Is5+hSVf0fazob47yitCXOW0i0S4lX2aySa3//2ZpZ2B2p8Z9r6aH+qlbHwEnAe1WjYIV+fX1ZHGSyZFIOIAldIGHzRqNRe7a5dGFGkxTm2Eqwpl5a7wpA+tKtAoSYMIflx4DknS3OHcUgnzJpDtIuWAX21p1LmRt0RpAWCKvOmrfTbmlgBFQfKgSzRmVJ9N2SFKob8NSDCn8gx9FZNWbDnVPeb7/AuD3wxgnxHs9shtOFuNJF1v8BAoJzKoRoN+8eRgcXtxBCR8JkvDszp503cCpyQN4bMURbv20q9hL37F3zQc9ehIx5mRbPkBJI86Cz+zVL4dOKDwT0K7jMEtwFp6nqRc9Mkwe/40OXEQUYQsW2YEyJ2GbF5juXibhMxt4WUtQNy4Ocg+blZ51zmwCrAiVCiQvl5sNq8CkzLhtXDY04lmhhCoMFOU4GN36yD1rONGTYCFx4XD7pOnSlJpE2gGt6ASIl+pf+Gk30GoxqgS+yHR5Ot24tMVKgh+bmzmIAwV4eiJUuXwDEb+lCbNq2JSR1lA11tMyqgJSQHK9rl0gmZD9IZCo407r0TNNO7hMPUYBRXXeqThcUVNvrsvhP3XgJkaGf9wOrx1vq3yJEp711nksL2AIfvHPk=
  - secure: jTAEs/ENMHAAkWAldAOpZg2r3q1Itt+VtLWEqnMkC8IwxK1tdkyUXnRVnh5P+EQujUITMVSZqbbUPFYyA+02USUbcx8zAe6sXRELOmN6U6GlPZrVPDBPkeGFEwlKkHeQ8DMcd2yOofulloeGU1MQcJN7QycnBlNOO8vWOE64RqD/yih1yWPz8R0SFSwdveM9QH/l8gwf0V1pSG9H+5x1Mjn6YKxl8dicyNCCGrT9KsxH3gShSXX7cdl6Srt/DvKyQ+JQ08Z/7nVQ0wemlftMFKEBpfDuDdaaCAzDeO6WdLNChq4yvWkRhpvGPVlpgTWQ9eGgKzIPchjNJallvH9BqXQ3ZRs4w7NS3afjJAvK0P0zKItoCvUlDLCyflxXqqfN2hGa7DiW7p/WBRu/FJBsElacy7QrVXGH1QDIi5vXFGWzzJRsPGBf71qPlFpImCXVeQ0SFNQgwQSwHHwTrfc755mN1vuoggu/fOZ9Up6/SpsqmOTnVmgiBNNZnuMjzLyCUxSQ7adypwl82rwwG85xMc3r9YzbDwvdatLoJnmFzY74C51h97gq4rs15kK6HnxCP3Hhz/avaGK2FnzTieTyMJFsgWuk9D75Tkp706lJlSUw6EprYTRZhntST1YKTtrMGliRT0ymHvu2sP1Ec1Jd4EtWN9D5pDxmoClxt0KqYqM=
script:
- mvn clean package -U
- docker build -t "$DOCKER_IMAGE" .
after_success:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push "$DOCKER_IMAGE"
