# Use root/example as user/password credentials
version: '3.1'

services:
  
  mongo:
    image: mongo:3.4
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: rso26root
      MONGO_INITDB_ROOT_PASSWORD: rso26pw
    ports:
      - 26001:27017

  mongo-express:
    image: mongo-express:0.49.0
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: rso26root
      ME_CONFIG_MONGODB_ADMINPASSWORD: rso26pw