apiVersion: apps/v1
kind: Deployment
metadata:
  name: geolocation-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: geolocation
  template:
    metadata:
      labels:
        app: geolocation
    spec:
      containers:
        - image: rso26/geolocation:1.0.0-SNAPSHOT-5.1
          name: geolocation
          env:
            - name: KUMULUZEE_DISCOVERY_CLUSTER
              value: gcloud
            - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
              value: http://etcd:2379
          ports:
            - containerPort: 8084
              name: server
              protocol: TCP
---

apiVersion: v1
kind: Service
metadata:
  name: geolocation
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: server
  selector:
    app: geolocation
